Updates

diff --git a/bin/go-jwst-imaging-stage-3 b/bin/go-jwst-imaging-stage-3
--- a/bin/go-jwst-imaging-stage-3
+++ b/bin/go-jwst-imaging-stage-3
@@ -123,6 +123,7 @@ for (( i = 0; i < ${#dataset_names[@]}; i++ )); do
     
 done
 
+
 # Run step 1
 dir_out="calibrated3_mosaics"
 proc_args=()
@@ -141,6 +142,96 @@ if [[ ${#files_out[@]} -eq 0 ]]; then
     echo "Error! Failed to produce the output files: \"$dir_out/jw*_obs*_*/jw*_obs*_*_i2d.fits\""
     exit 255
 fi
+
+
+# Run step 2
+for (( i = 0; i < ${#files_out[@]}; i++ )); do
+    
+    # obtain galaxy seed image
+    this_file_in="${files_out[i]}"
+    this_file_out=$(echo "$this_file_in" | perl -p -e 's/\.fits$//g')"_remstriping_galaxy_seed_image.fits"
+    if [[ ! -f "$this_file_out" ]] || [[ $overwrite -gt 0 ]]; then
+        echo $script_dir/remstriping "$this_file_in" \
+            --no-apply-flat --no-inplace \
+            --output-suffix remstriping --smooth 3.0
+        $script_dir/remstriping "$this_file_in" \
+            --no-apply-flat --no-inplace \
+            --output-suffix remstriping --smooth 3.0
+    fi
+    if [[ ! -f "$this_file_out" ]]; then
+        echo "Error! Failed to produce the output files: \"$this_file_out\""
+        exit 255
+    fi
+    
+    seed_image="$this_file_out"
+    
+    # find all associated cal.fits and rate.fits, mask them with source emission
+    asn_dir=$(dirname "$this_file_in")
+    asn_file=${asn_dir}_asn.json
+    asn_cal_images=($(cat "$asn_file" | grep "expname" | perl -p -e 's%[^0-9a-zA-Z_/.+-]% %g' | awk '{print $2}'))
+    asn_rate_images=()
+    masked_rate_images=()
+    for (( k = 0; k < ${#asn_cal_images[@]}; k++ )); do
+        asn_rate=$(echo "${asn_cal_images[k]}" | perl -p -e 's%/calibrated2_cals/%/calibrated1_rates/%g' | perl -p -e 's%_cal.fits$%_rate.fits%g')
+        masked_rate=$(echo "$asn_rate" | perl -p -e 's%\.fits$%%g')"_masked_source_emission.fits"
+        # make source-emission-masked rate image
+        if [[ ! -f "$masked_rate" ]] || [[ $overwrite -gt 0 ]]; then
+            echo $script_dir/util_mask_rate_data_with_seed_image.py \
+                "$asn_rate" \
+                "$seed_image" \
+                "$masked_rate"
+            $script_dir/util_mask_rate_data_with_seed_image.py \
+                "$asn_rate" \
+                "$seed_image" \
+                "$masked_rate"
+        fi
+        if [[ ! -f "$masked_rate" ]]; then
+            echo "Error! Failed to produce the output files: \"$masked_rate\""
+            exit 255
+        fi
+        asn_rate_images+=("$asn_rate")
+        masked_rate_images+=("$masked_rate")
+    done
+    
+    # loop rate image dir, merge all other source-emission-masked rate in this mosaic
+    for (( k = 0; k < ${#asn_rate_images[@]}; k++ )); do
+        asn_rate="${asn_rate_images[k]}"
+        merged_masked_rate=$(dirname "$asn_rate")"/merged_other_visits_mirimage_rate_masked_source_emission.fits"
+        # merge source-emission-masked rate images
+        if [[ ! -f "$merged_masked_rate" ]] || [[ $overwrite -gt 0 ]]; then
+            this_dataset_name=$(basename "$asn_rate" | perl -p -e 's/_rate.fits//g')
+            other_masked_rates=()
+            for (( m = 0; m < ${#masked_rate_images[@]}; m++ )); do
+                if [[ "${masked_rate_images[m]}" != *"this_dataset_name"* ]]; then
+                    other_masked_rates+=("${masked_rate_images[m]}")
+                fi
+            done
+            echo $script_dir/util_merge_source_emission_masked_rate_data.py \
+                ${other_masked_rates[@]} \
+                "$merged_masked_rate"
+            $script_dir/util_merge_source_emission_masked_rate_data.py \
+                ${other_masked_rates[@]} \
+                "$merged_masked_rate"
+            if [[ ! -f "$merged_masked_rate" ]]; then
+                echo "Error! Failed to produce the output files: \"$merged_masked_rate\""
+                exit 255
+            fi
+        fi
+    done
+    
+done
+
+
+
+
+
+
+
+
+
+
+
+
 
 
 
