Updates

diff --git a/bin/go-jwst-imaging-stage-2 b/bin/go-jwst-imaging-stage-2
--- a/bin/go-jwst-imaging-stage-2
+++ b/bin/go-jwst-imaging-stage-2
@@ -41,6 +41,7 @@ overwrite=0
 dataset_names=()
 user_flat_dir=""
 no_bkgsub=0
+no_sextractor=0
 while [[ $iarg -le $# ]]; do
     argstr=$(echo "${!iarg}" | tr '[:upper:]' '[:lower:]' | perl -p -e 's/_/-/g' | perl -p -e 's/^-([a-z]+.*)/--\1/g')
     if [[ "$argstr" == "--"* ]]; then
@@ -59,6 +60,9 @@ while [[ $iarg -le $# ]]; do
         elif [[ "$argstr" == "--no-bkgsub" ]]; then
             no_bkgsub=1
             echo "no_bkgsub = \"$no_bkgsub\""
+        elif [[ "$argstr" == "--no-sextractor" ]]; then
+            no_sextractor=1
+            echo "no_sextractor = \"$no_sextractor\""
         else
             echo "Unkonwn argument: ${!iarg}"
         fi
@@ -204,6 +208,30 @@ for (( i = 0; i < ${#dataset_names[@]}; i++ )); do
         #         exit 255
         #     fi
         # fi
+        
+    fi
+    
+    # Run step 4
+    # This step will use sextractor to detect bright sources and make catalog (catfile) for stage3 tweakreg
+    if [[ $no_sextractor -eq 0 ]]; then
+        
+        file_in="calibrated2_cals/${dataset_name}_cal.fits"
+        file_out="calibrated2_cals/${dataset_name}_cal_run_sextractor_classic_dir/SExtractor_OutputCatalogXY.csv"
+        proc_args=()
+        if [[ $overwrite -gt 0 ]]; then
+            proc_args+=(--overwrite)
+        fi
+        echo "*** Running ***" $script_dir/go-jwst-imaging-stage-2-step-4-do-sextractor.sh "$file_in" "${proc_args[@]}"
+        $script_dir/go-jwst-imaging-stage-2-step-4-do-sextractor.sh "$file_in" "${proc_args[@]}"
+        ret=$?
+        if [[ $ret -ne 0 ]]; then
+            echo "Error occurred?!"
+            exit 255
+        fi
+        if [[ ! -f "$file_out" ]] && [[ ! -L "$file_out" ]]; then
+            echo "Error! Failed to produce the output file: $file_out"
+            exit 255
+        fi
         
     fi
     
