Updates

diff --git a/bin/go-jwst-spectroscopy-stage-2 b/bin/go-jwst-spectroscopy-stage-2
--- a/bin/go-jwst-spectroscopy-stage-2
+++ b/bin/go-jwst-spectroscopy-stage-2
@@ -41,6 +41,8 @@ overwrite=0
 dataset_names=()
 user_flat_dir=""
 sourcecat=""
+segmap=""
+direct_image=""
 no_bkgsub=0
 no_sextractor=0
 while [[ $iarg -le $# ]]; do
@@ -63,6 +65,18 @@ while [[ $iarg -le $# ]]; do
             if [[ $iarg -le $# ]]; then
                 sourcecat=$(abspath "${!iarg}")
                 echo "sourcecat = \"$sourcecat\""
+            fi
+        elif [[ "$argstr" == "--segmap" ]]; then
+            iarg=$((iarg+1))
+            if [[ $iarg -le $# ]]; then
+                segmap=$(abspath "${!iarg}")
+                echo "segmap = \"$segmap\""
+            fi
+        elif [[ "$argstr" == "--direct-image" ]]; then
+            iarg=$((iarg+1))
+            if [[ $iarg -le $# ]]; then
+                direct_image=$(abspath "${!iarg}")
+                echo "direct_image = \"$direct_image\""
             fi
         elif [[ "$argstr" == "--no-bkgsub" ]]; then
             no_bkgsub=1
@@ -157,25 +171,26 @@ for (( i = 0; i < ${#dataset_names[@]}; i++ )); do
     file_in="calibrated1_rates/${dataset_name}_rate.fits"
     file_out="calibrated2_cals/${dataset_name}_cal.fits"
     proc_args=()
-    if [[ ! -z "$user_flat_dir" ]]; then
+    if [[ "$user_flat_dir"x != ""x ]]; then
         proc_args+=(--user-flat-dir "$user_flat_dir")
-    fi
-    if [[ ! -z "$sourcecat" ]]; then
-        proc_args+=(--sourcecat "$sourcecat")
     fi
     if [[ $overwrite -gt 0 ]]; then
         proc_args+=(--overwrite)
     fi
     exp_type=$(python -c "from jwst import datamodels; print(datamodels.open('$file_in').meta.exposure.type)" 2>/dev/null)
+    echo "exp_type = \"$exp_type\""
     if [[ x"$exp_type" == x"" ]]; then
         echo "Error! Could not get datamodel.meta.exposure.type for \"$file_in\"!"
         echo "Command executed: python -c \"from jwst import datamodels; print(datamodels.open(\'$file_in\').meta.exposure.type)\""
         exit 255
     fi
     if [[ "$exp_type" == "NRS_MSATA" ]] || [[ "$exp_type" == "NRS_TACONFIRM" ]]; then
+        
         echo "*** Running ***" python $script_dir/go-jwst-imaging-stage-2-step-1.py "$file_in" "$file_out" "${proc_args[@]}"
         python $script_dir/go-jwst-imaging-stage-2-step-1.py "$file_in" "$file_out" "${proc_args[@]}"
+        
     elif [[ "$exp_type" == "NRS_MSASPEC" ]]; then
+        
         msa_name=$(echo "$dataset_name" | perl -p -e 's/^(jw[0-9]+)_([0-9]+)_([0-9]+)_([a-zA-Z0-9]+)$/\1/g')
         msa_file=$(find "auxiliary" -maxdepth 1 -mindepth 1 -name "${msa_name}_*_msa.fits" | tail -n 1)
         if [[ x"$msa_file" == x"" ]]; then
@@ -185,9 +200,53 @@ for (( i = 0; i < ${#dataset_names[@]}; i++ )); do
         proc_args+=(--msa-meta-file "$msa_file")
         echo "*** Running ***" python $script_dir/go-jwst-spectroscopy-stage-2-step-1.py "$file_in" "$file_out" "${proc_args[@]}"
         python $script_dir/go-jwst-spectroscopy-stage-2-step-1.py "$file_in" "$file_out" "${proc_args[@]}"
-    else
+        
+    elif [[ "$exp_type" == "NRC_WFSS" ]]; then
+        
+        # use user input sourcecat or find sourcecat from ../processing_NIRCam_WFSS_direct_imaging/calibrated3_mosaics/
+        
+        pronum_obsnum_visnum=($(echo "$dataset_name" | perl -p -e 's/^jw([0-9]{5})([0-9]{3})([0-9]{3})_([0-9]+)_([0-9]+)_([a-zA-Z0-9]+)$/\1 \2 \3/g'))
+        if [[ ${#pronum_obsnum_visnum[@]} -ne 3 ]]; then
+            echo "Error! Could not match proposal number, observation number and visit number from the dataset name \"$dataset_name\"!"
+            exit 255
+        fi
+        pronum=${pronum_obsnum_visnum[0]}
+        obsnum=${pronum_obsnum_visnum[1]}
+        visnum=${pronum_obsnum_visnum[2]}
+        if [[ "$sourcecat"x == ""x ]]; then
+            sourcecat=$(ls "../processing_NIRCam_WFSS_direct_imaging/calibrated3_mosaics/"jw${pronum}_obs${obsnum}_visit${visnum}_NIRCAM_*/jw${pronum}_obs${obsnum}_visit${visnum}_NIRCAM_*_cat.ecsv 2>/dev/null | tail -n 1)
+        fi
+        if [[ "$sourcecat"x == ""x ]]; then
+            echo "Error! Could not find \"sourcecat\". Please set one!"
+            exit 255
+        else
+            proc_args+=(--sourcecat "$sourcecat")
+        fi
+        if [[ "$segmap"x == ""x ]]; then
+            segmap=$(ls "../processing_NIRCam_WFSS_direct_imaging/calibrated3_mosaics/"jw${pronum}_obs${obsnum}_visit${visnum}_NIRCAM_*/jw${pronum}_obs${obsnum}_visit${visnum}_NIRCAM_*_segm.fits 2>/dev/null | tail -n 1)
+        fi
+        if [[ "$segmap"x == ""x ]]; then
+            echo "Error! Could not find \"sourcecat\". Please set one!"
+            exit 255
+        else
+            proc_args+=(--segmap "$segmap")
+        fi
+        if [[ "$direct_image"x == ""x ]]; then
+            direct_image=$(ls "../processing_NIRCam_WFSS_direct_imaging/calibrated3_mosaics/"jw${pronum}_obs${obsnum}_visit${visnum}_NIRCAM_*/jw${pronum}_obs${obsnum}_visit${visnum}_NIRCAM_*_i2d.fits 2>/dev/null | tail -n 1)
+        fi
+        if [[ "$direct_image"x == ""x ]]; then
+            echo "Error! Could not find \"sourcecat\". Please set one!"
+            exit 255
+        else
+            proc_args+=(--direct-image "$direct_image")
+        fi
         echo "*** Running ***" python $script_dir/go-jwst-spectroscopy-stage-2-step-1.py "$file_in" "$file_out" "${proc_args[@]}"
         python $script_dir/go-jwst-spectroscopy-stage-2-step-1.py "$file_in" "$file_out" "${proc_args[@]}"
+    else
+        
+        echo "*** Running ***" python $script_dir/go-jwst-spectroscopy-stage-2-step-1.py "$file_in" "$file_out" "${proc_args[@]}"
+        python $script_dir/go-jwst-spectroscopy-stage-2-step-1.py "$file_in" "$file_out" "${proc_args[@]}"
+        
     fi
     ret=$?
     if [[ $ret -ne 0 ]]; then
