Adding snowball manual region removal

diff --git a/bin/go-jwst-imaging-stage-1 b/bin/go-jwst-imaging-stage-1
--- a/bin/go-jwst-imaging-stage-1
+++ b/bin/go-jwst-imaging-stage-1
@@ -306,6 +306,22 @@ for (( i = 0; i < ${#dataset_names[@]}; i++ )); do
     #    fi
     # done
     
+    # Run step 6
+    file_in="calibrated1_rates/${dataset_name}_rate.fits"
+    file_out1="calibrated1_rates/${dataset_name}_rate_before_removing_snowballs.fits"
+    echo "*** Running ***" $script_dir/go-jwst-imaging-stage-1-step-6-remove-snowballs "$file_in"
+    $script_dir/go-jwst-imaging-stage-1-step-6-remove-snowballs.sh "$file_in"
+    if [[ $? -ne 0 ]]; then
+        echo "Error?! Please check previous messages."
+        exit 255
+    fi
+    # for file_out in "$file_out1" "$file_out2"; do
+    #    if [[ ! -f "$file_out" ]] && [[ ! -L "$file_out" ]]; then
+    #        echo "Error! Failed to produce the output file: $file_out"
+    #        exit 255
+    #    fi
+    # done
+    
     echo cd ../
     cd ../
     
