Updates

diff --git a/bin/go-jwst-imaging-stage-3 b/bin/go-jwst-imaging-stage-3
--- a/bin/go-jwst-imaging-stage-3
+++ b/bin/go-jwst-imaging-stage-3
@@ -135,145 +135,98 @@ if [[ $ret -ne 0 ]]; then
     echo "Error occurred?!"
     exit 255
 fi
-files_out=($(find $dir_out -maxdepth 2 -mindepth 2 -type f -name "jw*_obs*_*_i2d.fits"))
+files_out=($(find $dir_out -maxdepth 2 -mindepth 2 -type f -name "jw*_obs*_*_i2d.fits" | sort -V | grep -v '+'))
 if [[ ${#files_out[@]} -eq 0 ]]; then
     echo "Error! Failed to produce the output files: \"$dir_out/jw*_obs*_*/jw*_obs*_*_i2d.fits\""
     exit 255
 fi
 
 
-# Run step 2, mask source emission and produce darkobs, for MIRI only
+# Store mosaic images
+mosaic_images=()
 for (( i = 0; i < ${#files_out[@]}; i++ )); do
+    mosaic_images+=("${files_out[i]}")
+done
+
+
+# Mask source emission and produce darkobs rate, for MIRI only
+for (( i = 0; i < ${#mosaic_images[@]}; i++ )); do
     
     # mosaic_image
-    mosaic_image="${files_out[i]}"
+    mosaic_image="${mosaic_images[i]}"
     if [[ "$mosaic_image" != *"MIRI"* ]]; then
        continue
     fi
     
-    # obtain galaxy seed image
-    this_file_in="$mosaic_image"
-    this_file_out=$(echo "$this_file_in" | perl -p -e 's/\.fits$//g')"_remstriping_galaxy_seed_image.fits"
-    this_dir_out=$(dirname "$this_file_out")
-    if [[ ! -f "$this_file_out" ]] || [[ $overwrite -gt 0 ]]; then
-        echo $script_dir/remstriping "$this_file_in" \
-            --no-apply-flat \
-            --no-inplace \
-            --output-dir "$this_dir_out" \
-            --output-suffix "remstriping" \
-            --smooth 3.0
-        $script_dir/remstriping "$this_file_in" \
-            --no-apply-flat \
-            --no-inplace \
-            --output-dir "$this_dir_out" \
-            --output-suffix "remstriping" \
-            --smooth 3.0
-    fi
-    if [[ ! -f "$this_file_out" ]]; then
-        echo "Error! Failed to produce the output files: \"$this_file_out\""
-        exit 255
-    fi
+    mosaic_asn=$(dirname "$mosaic_image")"_asn.json"
     
-    seed_image="$this_file_out"
-    
-    # find all associated cal.fits and rate.fits, mask them with source emission
-    asn_dir=$(dirname "$this_file_in")
-    asn_file=${asn_dir}_asn.json
-    asn_cal_images=($(cat "$asn_file" | grep "expname" | perl -p -e 's%[^0-9a-zA-Z_/.+-]% %g' | awk '{print $2}'))
-    asn_rate_images=()
-    masked_rate_images=()
-    for (( k = 0; k < ${#asn_cal_images[@]}; k++ )); do
-        asn_rate=$(echo "${asn_cal_images[k]}" | perl -p -e 's%/calibrated2_cals/%/calibrated1_rates/%g' | perl -p -e 's%_cal.fits$%_rate.fits%g')
-        masked_rate=$(echo "$asn_rate" | perl -p -e 's%\.fits$%%g')"_masked_source_emission.fits"
-        # make source-emission-masked rate image
-        if [[ ! -f "$masked_rate" ]] || [[ $overwrite -gt 0 ]]; then
-            echo $script_dir/util_mask_rate_data_with_seed_image.py \
-                "$asn_rate" \
-                "$seed_image" \
-                "$masked_rate"
-            $script_dir/util_mask_rate_data_with_seed_image.py \
-                "$asn_rate" \
-                "$seed_image" \
-                "$masked_rate"
-        fi
-        if [[ ! -f "$masked_rate" ]]; then
-            echo "Error! Failed to produce the output files: \"$masked_rate\""
-            exit 255
-        fi
-        asn_rate_images+=("$asn_rate")
-        masked_rate_images+=("$masked_rate")
-    done
-    
-    # loop rate image dir, merge all other source-emission-masked rate in this mosaic
-    for (( k = 0; k < ${#asn_rate_images[@]}; k++ )); do
-        asn_rate="${asn_rate_images[k]}"
-        merged_masked_rate=$(dirname "$asn_rate")"/merged_other_visits_rate_masked_source_emission.fits"
-        merged_masked_rate_list_file=$(echo "$merged_masked_rate" | perl -p -e 's/\.fits$/.list.txt/g')
-        # merge source-emission-masked rate images
-        if [[ ! -f "$merged_masked_rate" ]] || [[ $overwrite -gt 0 ]]; then
-            this_dataset_name=$(basename "$asn_rate" | perl -p -e 's/_rate.fits//g')
-            other_masked_rates=()
-            for (( m = 0; m < ${#masked_rate_images[@]}; m++ )); do
-                if [[ "${masked_rate_images[m]}" != *"this_dataset_name"* ]]; then
-                    other_masked_rates+=("${masked_rate_images[m]}")
-                fi
-            done
-            echo $script_dir/util_merge_source_emission_masked_rate_data.py \
-                ${other_masked_rates[@]} \
-                "$merged_masked_rate"
-            $script_dir/util_merge_source_emission_masked_rate_data.py \
-                ${other_masked_rates[@]} \
-                "$merged_masked_rate"
-            echo "# $script_dir/util_merge_source_emission_masked_rate_data.py" > "$merged_masked_rate_list_file"
-            for (( m = 0; m < ${#other_masked_rates[@]}; m++ )); do
-                echo "${other_masked_rates[m]}" >> "$merged_masked_rate_list_file"
-            done
-            if [[ ! -f "$merged_masked_rate" ]]; then
-                echo "Error! Failed to produce the output files: \"$merged_masked_rate\""
-                exit 255
-            fi
-        fi
-    done
-    
-    # loop rate image dir, reprocess pipeline stage2
-    redone_cal_files=()
-    for (( k = 0; k < ${#asn_rate_images[@]}; k++ )); do
-        asn_rate="${asn_rate_images[k]}"
-        asn_cal="${asn_cal_images[k]}"
-        merged_masked_rate=$(dirname "$asn_rate")"/merged_other_visits_rate_masked_source_emission.fits"
-        output_recal=$(echo "$asn_cal" | perl -p -e 's/_cal.fits$/_cal_bkgsub_with_source_emission_mask.fits/g')
-        
-        if [[ ! -f "$output_recal" ]] || [[ $overwrite -gt 0 ]]; then
-            proc_args=(--darkobs "$merged_masked_rate")
-            if [[ $overwrite -gt 0 ]]; then
-                proc_args+=(--overwrite)
-            fi
-            echo "*** Running ***" $script_dir/go-jwst-imaging-stage-2-step-3-redo-bkgsub.py \
-                "$asn_rate" \
-                "$output_recal" \
-                "${proc_args[@]}"
-            $script_dir/go-jwst-imaging-stage-2-step-3-redo-bkgsub.py \
-                "$asn_rate" \
-                "$output_recal" \
-                "${proc_args[@]}"
-            if [[ ! -f "$output_recal" ]] && [[ ! -L "$output_recal" ]]; then
-                echo "Error! Failed to produce the output file: $output_recal"
-                exit 255
-            fi
-        fi
-        redone_cal_files+=("$output_recal")
-    done
-    
-    # redo mosaic
-    redone_dir_out="calibrated3_mosaics_redone_with_source_emission_mask"
     proc_args=()
     if [[ $overwrite -gt 0 ]]; then
         proc_args+=(--overwrite)
     fi
-    echo "*** Running ***" $script_dir/go-jwst-imaging-stage-3-step-1.py ${redone_cal_files[@]} $redone_dir_out "${proc_args[@]}"
-    $script_dir/go-jwst-imaging-stage-3-step-1.py ${redone_cal_files[@]} $redone_dir_out "${proc_args[@]}"
+    echo "*** Running ***" $script_dir/go-jwst-imaging-stage-3-step-2-make-dark-rates.sh \
+        "$mosaic_image" "$mosaic_asn" "${proc_args[@]}"
+    $script_dir/go-jwst-imaging-stage-3-step-2-make-dark-rates.sh \
+        "$mosaic_image" "$mosaic_asn" "${proc_args[@]}"
     
 done
+
+
+# Merge multi-obs same-instrument-filter darkobs rates, for MIRI only
+for (( i = 0; i < ${#mosaic_images[@]}; i++ )); do
+    
+    # mosaic_image
+    mosaic_image="${mosaic_images[i]}"
+    if [[ "$mosaic_image" != *"MIRI"* ]]; then
+       continue
+    fi
+    
+    mosaic_asn=$(dirname "$mosaic_image")"_asn.json"
+    
+    instrument_filter=($(dirname "$mosaic_image" | cut -d '_' -f 3-4))
+    
+    multiobs_mosaic_asn=($(ls $(dirname "${mosaic_asn}")/jw*_obs*_${instrument_filter}"_asn.json"))
+    
+    echo "multiobs_mosaic_asn = ${multiobs_mosaic_asn[@]} (${#multiobs_mosaic_asn[@]})"
+    
+    proc_args=()
+    if [[ $overwrite -gt 0 ]]; then
+        proc_args+=(--overwrite)
+    fi
+    echo "*** Running ***" $script_dir/go-jwst-imaging-stage-3-step-3-merge-dark-rates.sh \
+        ${multiobs_mosaic_asn[@]} "${proc_args[@]}"
+    $script_dir/go-jwst-imaging-stage-3-step-3-merge-dark-rates.sh \
+        ${multiobs_mosaic_asn[@]} "${proc_args[@]}"
+    
+done
+
+
+# Get _cal_bkgsub_with_source_emission_mask.fits
+redo_files_in=()
+for (( i = 0; i < ${#dataset_names[@]}; i++ )); do
+    dataset_name="${dataset_names[i]}"
+    redo_files_in+=("$dataset_name/calibrated2_cals/${dataset_name}_cal_bkgsub_with_source_emission_mask.fits")
+done
+
+
+# Redo step 1 mosaic
+redo_dir_out="calibrated3_mosaics_redone_with_source_emission_mask"
+proc_args=()
+if [[ $overwrite -gt 0 ]]; then
+    proc_args+=(--overwrite)
+fi
+echo "*** Running ***" $script_dir/go-jwst-imaging-stage-3-step-1.py ${redo_files_in[@]} $redo_dir_out "${proc_args[@]}"
+$script_dir/go-jwst-imaging-stage-3-step-1.py ${redo_files_in[@]} $redo_dir_out "${proc_args[@]}"
+ret=$?
+if [[ $ret -ne 0 ]]; then
+    echo "Error occurred?!"
+    exit 255
+fi
+redo_files_out=($(find $redo_dir_out -maxdepth 2 -mindepth 2 -type f -name "jw*_obs*_*_i2d.fits" | sort -V | grep -v '+'))
+if [[ ${#redo_files_out[@]} -eq 0 ]]; then
+    echo "Error! Failed to produce the output files: \"$redo_dir_out/jw*_obs*_*/jw*_obs*_*_i2d.fits\""
+    exit 255
+fi
 
 
 
