Updates

diff --git a/bin/go-jwst-nircam-stage-1 b/bin/go-jwst-nircam-stage-1
--- a/bin/go-jwst-nircam-stage-1
+++ b/bin/go-jwst-nircam-stage-1
@@ -44,4 +44,7 @@ done
 # Run Python script
 python $script_dir/go-jwst-nircam-stage-1-task-1.py
 
-
+ret=$?
+if [[ $ret -ne 0 ]]; then
+    echo "Error occurred?!"
+fi
