Updates

diff --git a/bin/go-jwst-spectroscopy-stage-2 b/bin/go-jwst-spectroscopy-stage-2
--- a/bin/go-jwst-spectroscopy-stage-2
+++ b/bin/go-jwst-spectroscopy-stage-2
@@ -156,9 +156,13 @@ for (( i = 0; i < ${#dataset_names[@]}; i++ )); do
     if [[ $overwrite -gt 0 ]]; then
         proc_args+=(--overwrite)
     fi
-    #exp_type=$(python -c "from jwst import datamodels; with datamodels.open('$file_in') as model: print(model.meta.exposure.type)")
-    #if [[ "$exp_type" == "NRS_MSATA" ]]
-    if [[ "$dataset_name" == *"_nrs1" ]] || [[ "$dataset_name" == *"_nrs2" ]]; then
+    #exp_type=$(python -c "from jwst import datamodels; print(datamodels.open('$file_in').meta.exposure.type)" 2>/dev/null)
+    if [[ x"$exp_type" == x"" ]]/; then
+        echo "Error! Could not get datamodel.meta.exposure.type for \"$file_in\"!"
+        exit 255
+    fi
+    if [[ "$exp_type" == "NRS_MSATA" ]]; then
+    #if [[ "$dataset_name" == *"_nrs1" ]] || [[ "$dataset_name" == *"_nrs2" ]]; then
         echo "*** Running ***" python $script_dir/go-jwst-imaging-stage-2-step-1.py "$file_in" "$file_out" "${proc_args[@]}"
         python $script_dir/go-jwst-imaging-stage-2-step-1.py "$file_in" "$file_out" "${proc_args[@]}"
     else
