Updates

diff --git a/bin/go-jwst-imaging-stage-1 b/bin/go-jwst-imaging-stage-1
--- a/bin/go-jwst-imaging-stage-1
+++ b/bin/go-jwst-imaging-stage-1
@@ -78,6 +78,15 @@ if [[ ${#dataset_names[@]} -eq 0 ]]; then
             dataset_names+=("$found_dirname")
         fi
     done
+else
+    for (( i = 0; i < ${#dataset_names[@]}; i++ )); do
+        dataset_name="${dataset_names[i]}"
+        $script_dir/go-jwst-parse-dataset-name.py "$dataset_name" > /dev/null 2>&1
+        if [[ $? -ne 0 ]]; then
+            echo "Error! The input dataset name \"$dataset_name\" seems incorrect?"
+            exit 255
+        fi
+    done
 fi
 
 if [[ ${#dataset_names[@]} -eq 0 ]]; then
